### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by syahdeini** [davido/bazel-build-gerrit#1]
everytime I do `apk add`  I will have this error
```
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
```
how to install package without sudo?

**Comment by davido** [comment]
Something similar to: https://github.com/fluent/fluentd-docker-image/issues/21? Itworks here,
but can you try to add:

```
  USER root
```

before `RUN apk` line?

**Comment by JoseCage** [comment]
>  USER root

Worked for me. Thanks
